spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/upbit
    username: bit
    password: passwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true



server:
  port: 8087 #set your port





